version: 0.2

phases:
  pre_build:
    commands:
      - export ANDROID_HOME=/path/to/your/android/sdk
      - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes